# 请求域名
request:
  global:
    domain: "https://www.baidu.com"

spring:
  cloud:
    gateway:
      routes:
        - id: baidu
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/baidu/**
          uri: lb://baidu-feign
        # 自定义地址
          local: http://localhost:8080

